// <auto-generated />
using System;
using ConversationalAI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConversationalAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316202916_SeededData")]
    partial class SeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("ConversationalAI.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 14, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 15, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ConversationalAI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            ProductId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CartId = 2,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            CartId = 2,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            CartId = 2,
                            ProductId = 12,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("ConversationalAI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gadgets, devices, and accessories",
                            Title = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel for all ages and styles",
                            Title = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Everything for your living space",
                            Title = "Home & Garden"
                        });
                });

            modelBuilder.Entity("ConversationalAI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Over-ear noise cancelling headphones",
                            Price = 89.99m,
                            Quantity = 40,
                            Title = "Wireless Headphones"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Tenkeyless with brown switches",
                            Price = 119.99m,
                            Quantity = 25,
                            Title = "Mechanical Keyboard"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "7-in-1 multiport adapter",
                            Price = 34.99m,
                            Quantity = 60,
                            Title = "USB-C Hub"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "HD webcam with built-in mic",
                            Price = 59.99m,
                            Quantity = 35,
                            Title = "Webcam 1080p"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "100% organic cotton t-shirt",
                            Price = 19.99m,
                            Quantity = 100,
                            Title = "Classic White Tee"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Stretch chino trousers",
                            Price = 44.99m,
                            Quantity = 50,
                            Title = "Slim Chinos"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Lightweight packable puffer",
                            Price = 89.99m,
                            Quantity = 30,
                            Title = "Puffer Jacket"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Moisture-wicking ankle socks",
                            Price = 12.99m,
                            Quantity = 120,
                            Title = "Running Socks 3-Pack"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Minimalist pot with drainage hole",
                            Price = 14.99m,
                            Quantity = 75,
                            Title = "Ceramic Plant Pot"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Extra-large with juice groove",
                            Price = 24.99m,
                            Quantity = 45,
                            Title = "Bamboo Cutting Board"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Adjustable arm with USB charging",
                            Price = 39.99m,
                            Quantity = 55,
                            Title = "LED Desk Lamp"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Set of 3 soy wax candles",
                            Price = 29.99m,
                            Quantity = 80,
                            Title = "Scented Candle Set"
                        });
                });

            modelBuilder.Entity("ConversationalAI.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Percentage = 20m,
                            ProductId = 1,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Percentage = 15m,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ConversationalAI.Models.CartItem", b =>
                {
                    b.HasOne("ConversationalAI.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConversationalAI.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConversationalAI.Models.Product", b =>
                {
                    b.HasOne("ConversationalAI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ConversationalAI.Models.Sale", b =>
                {
                    b.HasOne("ConversationalAI.Models.Category", "Category")
                        .WithMany("Sales")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConversationalAI.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConversationalAI.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ConversationalAI.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ConversationalAI.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
